nodes = [
  { :hostname => 'kube-master',   :ip => '192.168.33.100', :ram => 2048 },
  { :hostname => 'kube-node1',    :ip => '192.168.33.201', :ram => 2048 },
  { :hostname => 'kube-node2',    :ip => '192.168.33.202', :ram => 2048 }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "centos/7";
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network "private_network", ip: node[:ip]
      memory = node[:ram] ? node[:ram] : 256;
      nodeconfig.vm.provider :virtualbox do |vb|
        vb.customize [
          "modifyvm", :id,
          "--memory", memory.to_s,
          "--cpus", "2"
        ]
      end
    end
  end
end
